// src/App.vue
<template>
    <section id="app">
        <section>
            <router-view name="body"></router-view>
        </section>
    </section>
</template>
<script>
import { mapGetters, mapActions } from 'vuex';
import api from 'utils/api';
export default {
    created () {
        api.getPage({
            tip: 'a'
        })
        .then(res => {
            console.log(res);
        });
    }
}
</script>
<style lang="less">
@import 'style/global.less';
</style>

// react-mobx-starter/src/App.jsx
import React from 'react';
import { Link } from 'react-router-dom';
import api from 'api';
import Routes from './routes/Index';
import './global.less';

export default class App extends React.Component {
  componentDidMount() {
    api.test().then(res => {
      console.log('api test: ', res);
    });
  }
  render() {
    return (
      <section>
       <section>
          <Link to={'/home'}>home</Link>
          <br/>
          <Link to={'/mobx-example'}>mobx-example</Link>
        </section>
        <section>
          <Routes/>
        </section>
      </section>

    )
  }
}
