// react-redux-reactrouter-ts-starter/src/containers/Home.tsx
import React from 'react';
import { bindActionCreators } from 'redux';
import { connect } from 'react-redux'
import * as settingActions from 'actions/setting';
import { mergeProps } from 'utils/tools';
import Title from 'components/Title';
import { Route, Switch, Link, HashRouter as Router } from 'react-router-dom';

export interface Props {
    username?: string;
    updateUsername?: (username: string) => void;
}

export default connect(
    (state: any) => ({
        username: state.setting.username
    }),
    dispatch => bindActionCreators({...settingActions}, dispatch),
    mergeProps
)(
    class Home extends React.Component<Props> {
        render () {
            const { username, updateUsername } = this.props;
            return (
                <section>
                    <Title text={'title'}/>
                    <Link to={'room1'}>enter room</Link>
                    <div>
                        <button onClick={
                            () => {
                                updateUsername && updateUsername(username + '+');
                            }
                        }>dispatch an action!</button>
                        <div>
                            action: {username}
                        </div>
                    </div>

                </section>
            )
        }
    }
)

// src/containers/home/index.vue
<template>
    <section>
        <v-title title="title"></v-title>
        <a href="javascript:void(0);" @click="enterRoom">enter room</a>
        <div>
            <button @click="updateGreeter">dispatch an action!</button>
            <div>state: {{ greeter }} </div>
        </div>
    </section>
</template>
<script lang="ts">
import { mapGetters, mapActions } from 'vuex';
import vTitle from 'components/title.vue';
export default {
    components: { vTitle },
    methods: {
        ...mapActions(['setGreeter']),
        updateGreeter () {
            this.setGreeter(this.greeter + '+');
        },
        enterRoom () {
            this.$router.push('/room1');
        },
    },
    computed: {
        ...mapGetters(['greeter']),
    },
    created () {
        this.setGreeter('');
    },
}
</script>
