// vue-webpack/src/app.vue
<template>
  <section>
    <my-title>Vue Starter</my-title>
    <div>Hi, {{ user }}</div>
    <div>
      <router-link to="/">home</router-link>
      <router-link to="/list">list</router-link>
    </div>
  <section>
    <router-view name="body"></router-view>
  </section>
  </section>
</template>

<script>

import MyTitle from 'components/my-title';
import api from 'api';

export default {
  components: {
    MyTitle,
  },
  computed: {
    user() {
      return this.$store.getters.user;
    },
  },
  created() {
    this.$store.dispatch('setUser', 'abc');
    api.test().then(res => {
      console.log(res);
    });
  },
}
</script>

<style>
html {
  font-size: 16px;
}
</style>

// react-mobx-reactrouter-starter/src/App.jsx
import React from 'react';
import { Link } from 'react-router-dom';
import api from 'api';
import Routes from './routes/Index';

export default class App extends React.Component {
  componentDidMount() {
    api.test().then(res => {
      console.log('api test: ', res);
    });
  }
  render() {
    return (
      <section>
       <section>
          <Link to={'/home'}>home</Link>
          <br/>
          <Link to={'/list'}>list</Link>
        </section>
        <section>
          <Routes/>
        </section>
      </section>

    )
  }
}
